"""Walk-forward backtesting with full P&L simulation.

This script bridges the TWO backtesting systems:
  1. Weather Brain (ML model): services/model/ — trains XGBoost, produces
     probability forecasts per Kalshi strike.
  2. Trading execution: services/backtest/ — simulates fills against
     real Kalshi orderbook snapshots.

Walk-Forward Procedure
======================
                    ┌──────── Train ────────┐┌──── Test (day‑by‑day) ────┐
  Day 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┃━━━━━━━━━━━━━━━━━━━━━━━━━━━┃
                    TrainingSetBuilder.build  │  For each ASOS-HR obs:     │
                    QuantileSuite.fit         │   1. FeatureEngine → x_t   │
                                              │   2. QuantileSuite → q̂     │
                                              │   3. MonotonicMapper → q̂↑  │
                                              │   4. StrikePricer → P_raw  │
                                              │   5. Calibrator → P_cal    │
                                              │   6. TradingStrategy →     │
                                              │      signals vs market     │
                                              │   7. Settle vs CLI high    │
                                              └────────────────────────────┘

Strategy Abstraction
====================
To test a DIFFERENT model (not XGBoost), create a new subclass of
``TradingStrategy`` and override ``generate_signals()``.  The rest of the
pipeline (data loading, feature engineering, market snapshot lookup,
settlement, P&L reporting) is model-agnostic.

Usage (no CLI arguments — all config is hardcoded below):
    python -m services.model.backtest_pnl
"""

from __future__ import annotations

import logging
import math
import re
import sys
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

from services.core.config import load_config, configure_logging
from services.markets.kalshi_registry import (
    KALSHI_MARKET_REGISTRY,
    series_for_icao,
)
from services.model.constants import QUANTILE_ALPHAS
from services.model.data_loader import ModelDataLoader
from services.model.training_set_builder import TrainingSetBuilder
from services.model.quantile_suite import QuantileSuite
from services.model.monotonic_mapper import MonotonicMapper
from services.model.strike_pricer import StrikePricer
from services.model.calibrator import IsotonicCalibrator
from services.model.feature_engine import FeatureEngine
from services.model.time_utils import lst_climate_date

logger = logging.getLogger("backtest_pnl")


# =====================================================================
# ▸ HARDCODED CONFIGURATION — edit these to change the backtest
# =====================================================================

ICAO = "KMDW"                              # Station to backtest
START_DATE = date(2026,2,1)             # Earliest available obs
END_DATE = date(2026, 2, 27)               # Latest available obs
MIN_TRAINING_DAYS = 20                     # Train on first 20 days
EV_THRESHOLD_CENTS = 3                     # Min EV to place a trade
MAX_CONTRACTS_PER_SIGNAL = 10000             # Max contracts per trade
TAKER_FEE_RATE = 0.07                       # Kalshi taker fee: 7% of P*(1-P) per contract
MARKET_SNAPSHOTS_DIR = None                # Auto-detected from config
LOG_LEVEL = "INFO"

# XGBoost hyperparameter overrides (or None for defaults)
XGB_OVERRIDES: Optional[dict] = None


def _kalshi_taker_fee_cents(contracts: int, price_cents: float, rate: float = TAKER_FEE_RATE) -> int:
    """Kalshi taker fee: round_up(rate × C × P × (1-P)), where P is price in dollars.

    Fee peaks at 50¢ (max uncertainty) and drops toward 0 at 0¢ or 100¢.
    """
    if price_cents <= 0 or price_cents >= 100:
        return 0
    p = price_cents / 100.0
    fee_dollars = rate * contracts * p * (1 - p)
    return int(math.ceil(fee_dollars * 100))


# =====================================================================
# ▸ Trade signal dataclass
# =====================================================================

@dataclass
class TradeSignal:
    """One directional trade signal generated by a strategy."""
    climate_date: str          # LST climate day
    observation_time_utc: datetime
    event_ticker: str          # e.g. KXHIGHCHI-26FEB21
    market_ticker: str         # e.g. KXHIGHCHI-26FEB21-T42
    strike_f: float            # Strike temperature in °F
    side: str                  # "yes" or "no"
    p_cal: float               # Calibrated probability P(High ≥ strike)
    ev_cents: float            # Expected value in cents
    max_contracts: int = 1     # Number of contracts to attempt


@dataclass
class SimulatedFill:
    """One executed paper trade from the backtest."""
    climate_date: str
    observation_time_utc: datetime
    event_ticker: str
    market_ticker: str
    strike_f: float
    side: str
    contracts: int
    avg_price_cents: float     # What we paid per contract
    total_cost_cents: float
    p_cal: float               # Model's calibrated probability
    ev_cents: float            # Expected value at time of trade
    # Settlement (filled post-hoc)
    settled: bool = False
    settlement_value: int = 0  # 0 or 100
    pnl_cents: float = 0.0    # Per-contract P&L


# =====================================================================
# ▸ TradingStrategy — abstract base (swap XGBoost for any model)
# =====================================================================

class TradingStrategy(ABC):
    """Abstract trading strategy for the backtester.

    Subclass this and implement ``generate_signals()`` to plug in any
    prediction model.  The backtest harness handles:
      - Data loading and feature engineering
      - Market snapshot lookup for execution prices
      - Settlement against CLI ground-truth
      - P&L computation
    """

    @abstractmethod
    def fit(
        self,
        X_train: pd.DataFrame,
        y_train: pd.Series,
    ) -> None:
        """Train the model on training data."""

    @abstractmethod
    def generate_signals(
        self,
        feature_row: pd.Series,
        custom_intraday_max_f: float,
        strikes: list[float],
        market_snapshot: pd.DataFrame,
        event_ticker: str,
        climate_date: str,
    ) -> list[TradeSignal]:
        """Generate trade signals for one observation.

        Parameters
        ----------
        feature_row :          One row of features (from FeatureEngine).
        custom_intraday_max_f: Running max temperature in °F.
        strikes :              Available Kalshi strike temperatures.
        market_snapshot :      Market data (yes_bid, yes_ask, etc.) at this time.
        event_ticker :         The Kalshi event ticker for this day.
        climate_date :         LST climate date string.

        Returns
        -------
        List of TradeSignal objects.  Empty list = no trades.
        """


# =====================================================================
# ▸ XGBoostEVStrategy — the default Weather Brain strategy
# =====================================================================

class XGBoostEVStrategy(TradingStrategy):
    """Trade based on XGBoost quantile regression expected value.

    This is the Weather Brain strategy from MODELING_IDEA.MD §8–§10:
    1. Predict the remaining heating delta distribution (7 quantiles)
    2. Map onto Kalshi strikes → P(High ≥ S)
    3. Compare calibrated P to market price → EV
    4. Trade when EV > threshold
    """

    def __init__(
        self,
        alphas: tuple[float, ...] = QUANTILE_ALPHAS,
        xgb_params: Optional[dict] = None,
        ev_threshold_cents: float = 3,
        max_contracts: int = 10,
    ):
        self.alphas = alphas
        self.xgb_params = xgb_params
        self.ev_threshold = ev_threshold_cents
        self.max_contracts = max_contracts
        self.suite: Optional[QuantileSuite] = None
        self.calibrator: Optional[IsotonicCalibrator] = None
        self._mapper = MonotonicMapper(alphas)
        self._pricer = StrikePricer(alphas)

    def fit(self, X_train: pd.DataFrame, y_train: pd.Series) -> None:
        """Train the quantile suite + calibrator on training data."""
        # Split: 80% for XGBoost, 20% for early stopping validation
        n = len(X_train)
        es_split = max(1, int(n * 0.8))
        X_tr, y_tr = X_train.iloc[:es_split], y_train.iloc[:es_split]
        X_v,  y_v  = X_train.iloc[es_split:], y_train.iloc[es_split:]

        self.suite = QuantileSuite(alphas=self.alphas, xgb_params=self.xgb_params)
        self.suite.fit(X_tr, y_tr, X_v, y_v)

        # Calibrator: use validation set predictions as calibration data
        if len(X_v) > 5:
            raw_preds_cal = self.suite.predict(X_v)
            mono_preds_cal = self._mapper.transform_batch(raw_preds_cal)
            p_raw_cal = mono_preds_cal[0.50].astype(np.float64)
            y_binary_cal = (y_v.values > 0).astype(np.float64)

            self.calibrator = IsotonicCalibrator()
            try:
                self.calibrator.fit(
                    p_raw_cal=p_raw_cal,
                    y_outcome_cal=y_binary_cal,
                    train_index=X_tr.index,
                    cal_index=X_v.index,
                )
                logger.info("Calibrator fitted on %d validation rows.", len(X_v))
            except Exception as e:
                logger.warning("Calibrator fitting failed: %s — using raw probs.", e)
                self.calibrator = None
        else:
            logger.info("Not enough validation data for calibrator — using raw probs.")
            self.calibrator = None

    def generate_signals(
        self,
        feature_row: pd.Series,
        custom_intraday_max_f: float,
        strikes: list[float],
        market_snapshot: pd.DataFrame,
        event_ticker: str,
        climate_date: str,
    ) -> list[TradeSignal]:
        if self.suite is None:
            raise RuntimeError("Must call fit() before generate_signals().")

        # Stage 2: Quantile predictions
        raw_q = self.suite.predict_row(feature_row)

        # Stage 3: Monotonic mapping
        mono_q = self._mapper.transform(raw_q)

        # Stage 4: Strike pricing
        p_raw = self._pricer.price_all_strikes(strikes, custom_intraday_max_f, mono_q)

        # Stage 5: Calibration
        p_cal: dict[float, float] = {}
        if self.calibrator is not None and self.calibrator.is_fitted:
            for s, p in p_raw.items():
                p_cal[s] = float(self.calibrator.calibrate(p))
        else:
            p_cal = dict(p_raw)

        # Stage 6: Generate signals based on EV vs market prices
        signals: list[TradeSignal] = []
        obs_time = feature_row.get("observation_time_utc")

        for strike, p in p_cal.items():
            # Find matching market ticker in snapshot
            matching = market_snapshot[
                market_snapshot["subtitle"].apply(
                    lambda x: _subtitle_matches_strike(x, strike)
                )
            ]
            if matching.empty:
                continue

            row = matching.iloc[-1]  # Most recent snapshot
            yes_ask = float(row.get("yes_ask", 100))
            no_ask = float(row.get("no_ask", 100))
            market_ticker = str(row.get("market_ticker", ""))

            # EV calculations (in cents) — subtract Kalshi taker fee (formula-based)
            fee_yes = _kalshi_taker_fee_cents(1, yes_ask)
            fee_no = _kalshi_taker_fee_cents(1, no_ask)
            ev_yes = (p * 100) - yes_ask - fee_yes
            ev_no = ((1 - p) * 100) - no_ask - fee_no

            # Pick the better side if EV > threshold
            if ev_yes >= self.ev_threshold and ev_yes >= ev_no:
                signals.append(TradeSignal(
                    climate_date=climate_date,
                    observation_time_utc=obs_time,
                    event_ticker=event_ticker,
                    market_ticker=market_ticker,
                    strike_f=strike,
                    side="yes",
                    p_cal=p,
                    ev_cents=ev_yes,
                    max_contracts=self.max_contracts,
                ))
            elif ev_no >= self.ev_threshold:
                signals.append(TradeSignal(
                    climate_date=climate_date,
                    observation_time_utc=obs_time,
                    event_ticker=event_ticker,
                    market_ticker=market_ticker,
                    strike_f=strike,
                    side="no",
                    p_cal=p,
                    ev_cents=ev_no,
                    max_contracts=self.max_contracts,
                ))

        return signals


# =====================================================================
# ▸ Market snapshot helpers
# =====================================================================

def _subtitle_matches_strike(subtitle: str, strike_f: float) -> bool:
    """Check if a Kalshi subtitle corresponds to a given strike temp.

    Subtitles look like: '43° or above', '39° to 40°', '34° or below'.
    For 'X° or above' → strike = X.
    For 'X° to Y°' → strike = Y + 0.5 (bracket midpoint cap).
    """
    if pd.isna(subtitle):
        return False
    s = str(subtitle).strip().replace("°", "")
    # "X or above" → cap_strike = X
    m = re.match(r"(\d+)\s+or\s+above", s)
    if m:
        return float(m.group(1)) == strike_f
    # "X to Y" → cap_strike = Y + 0.5 (common Kalshi convention)
    m = re.match(r"(\d+)\s+to\s+(\d+)", s)
    if m:
        low, high = float(m.group(1)), float(m.group(2))
        # Match if strike is in this bucket range
        return low <= strike_f <= high + 0.5
    # "X or below" → cap_strike = X
    m = re.match(r"(\d+)\s+or\s+below", s)
    if m:
        return float(m.group(1)) == strike_f
    return False


def _parse_strikes_from_snapshots(snapshot_df: pd.DataFrame) -> list[float]:
    """Extract unique strike temperatures from market snapshot subtitles."""
    strikes = set()
    for subtitle in snapshot_df["subtitle"].dropna().unique():
        s = str(subtitle).strip().replace("°", "")
        m = re.match(r"(\d+)\s+or\s+above", s)
        if m:
            strikes.add(float(m.group(1)))
            continue
        m = re.match(r"(\d+)\s+to\s+(\d+)", s)
        if m:
            # Use the high end as the strike
            strikes.add(float(m.group(2)))
            continue
        m = re.match(r"(\d+)\s+or\s+below", s)
        if m:
            strikes.add(float(m.group(1)))
    return sorted(strikes)


def _load_market_snapshots(
    data_dir: Path,
    start_date: date,
    end_date: date,
    series_prefix: str,
) -> pd.DataFrame:
    """Load Kalshi market snapshots for the given date range + filter by series."""
    snap_dir = data_dir / "kalshi" / "market_snapshots"
    if not snap_dir.exists():
        logger.warning("Market snapshot directory not found: %s", snap_dir)
        return pd.DataFrame()

    import pyarrow.parquet as pq
    import pyarrow as pa

    start_str = start_date.isoformat()
    end_str = end_date.isoformat()
    files = sorted(snap_dir.glob("*.parquet"))
    files = [f for f in files if start_str <= f.stem <= end_str]

    if not files:
        logger.warning("No market snapshots for %s → %s.", start_str, end_str)
        return pd.DataFrame()

    tables = [pq.read_table(f) for f in files]
    df = pa.concat_tables(tables, promote_options="default").to_pandas()
    df["snapshot_ts_utc"] = pd.to_datetime(df["snapshot_ts_utc"], utc=True)

    # Filter to relevant series
    df = df[df["event_ticker"].str.startswith(series_prefix)].copy()
    df = df.sort_values("snapshot_ts_utc").reset_index(drop=True)
    logger.info(
        "Loaded %d market snapshots for %s [%s → %s].",
        len(df), series_prefix, start_str, end_str,
    )
    return df


def _find_closest_snapshot(
    snapshots: pd.DataFrame,
    observation_time: pd.Timestamp,
    event_ticker: str,
    lookback_minutes: int = 5,
) -> pd.DataFrame:
    """Find the closest market snapshot BEFORE the observation time.

    Returns the subset of snapshot rows for all strikes at that point.
    We look for the most recent snapshot within `lookback_minutes` of the obs.
    """
    cutoff = observation_time - pd.Timedelta(minutes=lookback_minutes)
    filtered = snapshots[
        (snapshots["event_ticker"] == event_ticker)
        & (snapshots["snapshot_ts_utc"] <= observation_time)
        & (snapshots["snapshot_ts_utc"] >= cutoff)
    ]
    if filtered.empty:
        # Expand search: any snapshot before obs time for this event
        filtered = snapshots[
            (snapshots["event_ticker"] == event_ticker)
            & (snapshots["snapshot_ts_utc"] <= observation_time)
        ]
    if filtered.empty:
        return pd.DataFrame()

    # Get the latest snapshot timestamp and return all rows at that time
    latest_ts = filtered["snapshot_ts_utc"].max()
    return filtered[filtered["snapshot_ts_utc"] == latest_ts]


def _event_ticker_for_date(climate_date_str: str, series_prefix: str) -> str:
    """Generate the expected Kalshi event ticker for a climate date.

    Format: KXHIGHCHI-26FEB21 (last 2 digits of year + uppercase month + day).
    """
    d = date.fromisoformat(climate_date_str)
    return f"{series_prefix}-{d.strftime('%y%b%d').upper()}"


# =====================================================================
# ▸ Settlement logic
# =====================================================================

def _settle_fills(
    fills: list[SimulatedFill],
    cli_labels: dict[str, int],
) -> list[SimulatedFill]:
    """Settle trades against CLI ground-truth highs.

    For each fill:
      - YES side: wins (payout=100) if CLI_High >= strike, loses (payout=0) otherwise
      - NO side:  wins (payout=100) if CLI_High < strike, loses (payout=0) otherwise
      - P&L = (payout - cost) × contracts - Kalshi taker fee (formula-based)
    """
    for f in fills:
        cli_high = cli_labels.get(f.climate_date)
        if cli_high is None:
            logger.warning("No CLI label for %s — cannot settle %s.", f.climate_date, f.market_ticker)
            continue

        f.settled = True
        if f.side == "yes":
            f.settlement_value = 100 if cli_high >= f.strike_f else 0
        else:  # "no"
            f.settlement_value = 100 if cli_high < f.strike_f else 0

        fee_cents = _kalshi_taker_fee_cents(f.contracts, f.avg_price_cents)
        f.pnl_cents = (f.settlement_value - f.avg_price_cents) * f.contracts - fee_cents

    return fills


# =====================================================================
# ▸ Main backtest orchestrator
# =====================================================================

def run_backtest(
    icao: str = ICAO,
    start_date: date = START_DATE,
    end_date: date = END_DATE,
    min_training_days: int = MIN_TRAINING_DAYS,
    strategy: Optional[TradingStrategy] = None,
) -> tuple[list[SimulatedFill], pd.DataFrame]:
    """Run the full walk-forward P&L backtest.

    Returns
    -------
    fills : list[SimulatedFill]
        All simulated trades, settled against CLI.
    summary_df : pd.DataFrame
        Per-day P&L summary.
    """
    # ── Setup ─────────────────────────────────────────────────────────
    config, config_path = load_config()
    data_dir = (config_path.parent / config.get("storage", {}).get("data_dir", "../data")).resolve()

    # Find station metadata
    mc = None
    for cfg in KALSHI_MARKET_REGISTRY.values():
        if cfg.icao == icao:
            mc = cfg
            break
    if mc is None:
        raise ValueError(f"ICAO {icao!r} not found in KALSHI_MARKET_REGISTRY.")

    series_prefix = mc.series_prefix

    if strategy is None:
        strategy = XGBoostEVStrategy(
            xgb_params=XGB_OVERRIDES,
            ev_threshold_cents=EV_THRESHOLD_CENTS,
            max_contracts=MAX_CONTRACTS_PER_SIGNAL,
        )

    # ── Step 1: Build training set (all available data) ───────────────
    logger.info("=" * 65)
    logger.info(" Walk-Forward P&L Backtest")
    logger.info("  Station        : %s (%s)", icao, mc.city)
    logger.info("  Data range     : %s → %s", start_date, end_date)
    logger.info("  Min train days : %d", min_training_days)
    logger.info("  Strategy       : %s", strategy.__class__.__name__)
    logger.info("=" * 65)

    builder = TrainingSetBuilder(
        data_dir=data_dir,
        icao=icao,
        lat=mc.lat,
        lon=mc.lon,
        tz=mc.tz,
    )
    X_full, y_full = builder.build(start_date, end_date, save_log=False)

    if X_full.empty:
        logger.error("Training set is empty — aborting.")
        return [], pd.DataFrame()

    # Print data quality summary
    report = builder.summary_report(X_full, y_full, start_date, end_date)
    logger.info("Data Quality:")
    for k, v in report.items():
        logger.info("  %-35s: %s", k, v)

    all_dates = sorted(X_full["climate_date_lst"].unique())
    n_dates = len(all_dates)
    logger.info("Total climate days with data: %d", n_dates)

    if n_dates < min_training_days + 1:
        logger.error(
            "Not enough days (%d) for train=%d + test≥1. Aborting.",
            n_dates, min_training_days,
        )
        return [], pd.DataFrame()

    # ── Step 2: Split into train / test by date ───────────────────────
    train_dates = all_dates[:min_training_days]
    test_dates = all_dates[min_training_days:]

    train_mask = X_full["climate_date_lst"].isin(train_dates)
    X_train = X_full[train_mask]
    y_train = y_full[train_mask]

    logger.info(
        "Train: %d days (%s → %s), %d rows",
        len(train_dates), train_dates[0], train_dates[-1], len(X_train),
    )
    logger.info(
        "Test:  %d days (%s → %s)",
        len(test_dates), test_dates[0], test_dates[-1],
    )

    # ── Step 3: Train the strategy ────────────────────────────────────
    logger.info("Training model...")
    strategy.fit(X_train, y_train)
    logger.info("Model training complete.")

    # ── Step 4: Load market snapshots for test period ─────────────────
    test_start = date.fromisoformat(test_dates[0])
    test_end = date.fromisoformat(test_dates[-1])
    # Load a buffer around test dates (snapshots start the evening before)
    snap_start = test_start - timedelta(days=1)
    snap_end = test_end + timedelta(days=1)

    snapshots = _load_market_snapshots(data_dir, snap_start, snap_end, series_prefix)

    # ── Step 5: Load CLI labels for settlement ────────────────────────
    loader = ModelDataLoader(data_dir, icao)
    cli_labels = loader.cli_label_map(start_date, end_date)
    logger.info("CLI labels available for %d days.", len(cli_labels))

    # ── Step 6: Walk through test days and generate signals ───────────
    all_fills: list[SimulatedFill] = []
    trade_log: list[dict] = []
    dedup_set: set[tuple[str, str, str]] = set()  # (date, ticker, side) for dedup

    for test_date_str in test_dates:
        test_mask = X_full["climate_date_lst"] == test_date_str
        X_test_day = X_full[test_mask]

        if X_test_day.empty:
            logger.info("[%s] No test rows — skipping.", test_date_str)
            continue

        # Generate the event ticker for this day
        event_ticker = _event_ticker_for_date(test_date_str, series_prefix)

        # Get available strikes from market snapshots for this event
        event_snaps = snapshots[snapshots["event_ticker"] == event_ticker]
        if event_snaps.empty:
            logger.info("[%s] No market snapshots for %s — skipping.", test_date_str, event_ticker)
            continue

        strikes = _parse_strikes_from_snapshots(event_snaps)
        if not strikes:
            logger.info("[%s] No strikes parsed from snapshots — skipping.", test_date_str)
            continue

        logger.info("[%s] %d strikes: %s", test_date_str, len(strikes), strikes)

        # Iterate through observations for the day
        day_signals = 0
        for idx, row in X_test_day.iterrows():
            obs_time = row["observation_time_utc"]
            custom_max = row["custom_intraday_max_f"]

            # Find closest market snapshot BEFORE this observation
            snap_at_obs = _find_closest_snapshot(
                snapshots, obs_time, event_ticker, lookback_minutes=10,
            )
            if snap_at_obs.empty:
                continue

            # Generate signals from strategy
            signals = strategy.generate_signals(
                feature_row=row,
                custom_intraday_max_f=custom_max,
                strikes=strikes,
                market_snapshot=snap_at_obs,
                event_ticker=event_ticker,
                climate_date=test_date_str,
            )

            for signal in signals:
                # Dedup: only trade each (date, market_ticker, side) once
                dedup_key = (test_date_str, signal.market_ticker, signal.side)
                if dedup_key in dedup_set:
                    continue
                dedup_set.add(dedup_key)

                # Simulate execution at the ask price
                if signal.side == "yes":
                    matching = snap_at_obs[
                        snap_at_obs["market_ticker"] == signal.market_ticker
                    ]
                    if matching.empty:
                        continue
                    exec_price = float(matching.iloc[-1]["yes_ask"])
                else:
                    matching = snap_at_obs[
                        snap_at_obs["market_ticker"] == signal.market_ticker
                    ]
                    if matching.empty:
                        continue
                    exec_price = float(matching.iloc[-1]["no_ask"])

                if exec_price <= 0 or exec_price >= 100:
                    continue  # Skip unfillable

                contracts = min(signal.max_contracts, 1)  # Conservative: 1 contract

                fee_cents = _kalshi_taker_fee_cents(contracts, exec_price)
                fill = SimulatedFill(
                    climate_date=test_date_str,
                    observation_time_utc=obs_time,
                    event_ticker=event_ticker,
                    market_ticker=signal.market_ticker,
                    strike_f=signal.strike_f,
                    side=signal.side,
                    contracts=contracts,
                    avg_price_cents=exec_price,
                    total_cost_cents=exec_price * contracts + fee_cents,
                    p_cal=signal.p_cal,
                    ev_cents=signal.ev_cents,
                )
                all_fills.append(fill)
                day_signals += 1

        logger.info("[%s] Filled %d trades.", test_date_str, day_signals)

    # ── Step 7: Settle all fills against CLI labels ───────────────────
    all_fills = _settle_fills(all_fills, cli_labels)

    # ── Step 8: Compute and display P&L ───────────────────────────────
    summary_df = _build_summary(all_fills, cli_labels, test_dates)

    return all_fills, summary_df


# =====================================================================
# ▸ P&L reporting
# =====================================================================

def _build_summary(
    fills: list[SimulatedFill],
    cli_labels: dict[str, int],
    test_dates: list[str],
) -> pd.DataFrame:
    """Build a per-day and aggregate P&L summary."""
    if not fills:
        logger.info("No fills — nothing to summarize.")
        return pd.DataFrame()

    records = []
    for f in fills:
        records.append({
            "climate_date": f.climate_date,
            "observation_time_utc": f.observation_time_utc,
            "event_ticker": f.event_ticker,
            "market_ticker": f.market_ticker,
            "strike_f": f.strike_f,
            "side": f.side,
            "contracts": f.contracts,
            "avg_price_cents": f.avg_price_cents,
            "total_cost_cents": f.total_cost_cents,
            "p_cal": f.p_cal,
            "ev_cents": f.ev_cents,
            "settled": f.settled,
            "settlement_value": f.settlement_value,
            "pnl_cents": f.pnl_cents,
        })

    df = pd.DataFrame(records)

    # ── Print results ─────────────────────────────────────────────────
    print("\n" + "=" * 80)
    print("BACKTEST RESULTS — Walk-Forward P&L")
    print("=" * 80)

    # Per-day summary
    daily = df.groupby("climate_date").agg(
        trades=("pnl_cents", "count"),
        total_cost=("total_cost_cents", "sum"),
        gross_pnl=("pnl_cents", "sum"),
        avg_ev=("ev_cents", "mean"),
        win_rate=("pnl_cents", lambda x: (x > 0).sum() / max(len(x), 1)),
    ).reset_index()

    # Add CLI high for context
    daily["cli_high_f"] = daily["climate_date"].map(cli_labels)

    print("\nPer-Day Summary:")
    print("-" * 80)
    for _, row in daily.iterrows():
        pnl = row["gross_pnl"]
        emoji = "✅" if pnl > 0 else ("⚠️" if pnl == 0 else "❌")
        print(
            f"  {emoji} {row['climate_date']} | CLI High: {row.get('cli_high_f', '?'):>3}°F | "
            f"Trades: {row['trades']:>3} | Cost: ${row['total_cost'] / 100:>7.2f} | "
            f"P&L: ${pnl / 100:>7.2f} | Avg EV: {row['avg_ev']:>5.1f}¢ | "
            f"Win: {row['win_rate']:>5.1%}"
        )

    print("-" * 80)

    # Aggregate summary
    settled = df[df["settled"]]
    total_trades = len(settled)
    total_cost = settled["total_cost_cents"].sum()
    total_pnl = settled["pnl_cents"].sum()
    wins = (settled["pnl_cents"] > 0).sum()
    losses = (settled["pnl_cents"] < 0).sum()
    win_rate = wins / max(total_trades, 1)
    avg_pnl_per_trade = total_pnl / max(total_trades, 1)

    print(f"\n{'Aggregate':^80}")
    print("-" * 80)
    print(f"  Total trades:        {total_trades}")
    print(f"  Wins / Losses:       {wins} / {losses}")
    print(f"  Win rate:            {win_rate:.1%}")
    print(f"  Total cost:          ${total_cost / 100:.2f}")
    print(f"  Gross P&L:           ${total_pnl / 100:.2f}")
    print(f"  P&L per trade:       ${avg_pnl_per_trade / 100:.2f}")
    print(f"  ROI:                 {total_pnl / max(total_cost, 1) * 100:.1f}%")

    # Cumulative P&L series
    print(f"\n  Cumulative P&L by day:")
    cum = 0.0
    for _, row in daily.iterrows():
        cum += row["gross_pnl"]
        bar = "█" * max(0, int(cum / 50))
        print(f"    {row['climate_date']}: ${cum / 100:>8.2f}  {bar}")

    print("=" * 80)

    return df


# =====================================================================
# ▸ Entry point
# =====================================================================

def main() -> int:
    configure_logging(LOG_LEVEL)
    try:
        fills, summary = run_backtest()
        if summary.empty:
            logger.info("Backtest produced no fills.")
        return 0
    except Exception:
        logger.exception("Backtest failed.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
