#cloud-config
# Minimal OS prep so the VM is ready for setup_collector/first_time_vm_setup.sh after SSH-ing in.
# cloud-config format handles apt locks and user setup natively.

system_info:
  default_user:
    name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

timezone: America/New_York

package_update: true

packages:
  - git
  - curl
  - ca-certificates
  - fail2ban
  - unattended-upgrades
  - docker-compose-plugin

runcmd:
  - curl -fsSL https://get.docker.com | sh
  - usermod -aG docker ubuntu
  - systemctl enable --now docker
  - echo "[cloud-init] Done. SSH in and run setup_collector/first_time_vm_setup.sh"
